name: Deploy Zero Budget Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend
        run: |
          TIMESTAMP_TAG="${IMAGE_NAME}:$(date +'%Y%m%d%H%M')"
          
          # Build the image with both latest and timestamp tags
          docker build -t "${IMAGE_NAME}:latest" -t "$TIMESTAMP_TAG" .

          # Output tags for debugging
          echo "Built Docker image with tags:"
          echo "${IMAGE_NAME}:latest"
          echo "$TIMESTAMP_TAG"

      - name: Push Docker Image to Docker Hub
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend
        run: |
          docker push "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:$(date +'%Y%m%d%H%M')"

      - name: Deploy
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          # Install Railway CLI
          curl -fsSL https://railway.app/install.sh | bash
          export PATH="$HOME/.railway/bin:$PATH"

          railway login --token $RAILWAY_API_TOKEN

          # Link the Railway project
          railway link --project <project_id>  # Replace <project_id> with your Railway project ID

          # Deploy the Docker image using the latest tag
          railway up --service zero-budget-backend --docker-image "${IMAGE_NAME}:latest"
