name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend:latest ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend:$(date +%Y%m%d%H%M)

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend:$(date +%Y%m%d%H%M)

      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          # Install Railway CLI
          curl -fsSL https://railway.app/install.sh | bash
          export PATH="$HOME/.railway/bin:$PATH"

          # Authenticate with Railway
          railway login --token $RAILWAY_API_TOKEN

          # Link the Railway project
          railway link --project <project_id>  # Replace <project_id> with your Railway project ID

          # Deploy the Docker image
          railway up --service zero-budget-backend --docker-image ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend:latest
