name: Deploy Zero Budget Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Generate Prisma Client
        run: yarn generate

      - name: Run Database Migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn migrate:deploy

      - name: Build the Application
        run: yarn build

      - name: Install Vercel CLI
        run: yarn global add -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token $VERCEL_TOKEN --org-id $VERCEL_ORG_ID --project-id $VERCEL_PROJECT_ID
