name: Deploy Zero Budget Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend
          DOCKER_TAG: latest
        run: |
          docker build -t "${IMAGE_NAME}:${DOCKER_TAG}" .

          # Output the tag for debugging
          echo "Built Docker image with tag: ${IMAGE_NAME}:${DOCKER_TAG}"

      - name: Push Docker Image to Docker Hub
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend
          DOCKER_TAG: latest
        run: |
          docker push "${IMAGE_NAME}:${DOCKER_TAG}"

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend
          DOCKER_TAG: latest
        run: |
          # Install Railway CLI
          curl -fsSL https://railway.app/install.sh | bash
          export PATH="$HOME/.railway/bin:$PATH"

          # Authenticate with Railway (no --token flag needed)
          railway login

          # Link the Railway project
          railway link --project 02cb3a1c-bfda-4c4c-bac5-7dc3a989e01e 

          # Deploy the Docker image using the specific tag
          railway up --service zero-budget-backend --docker-image "${IMAGE_NAME}:${DOCKER_TAG}"
