name: Deploy Zero Budget Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend
          DOCKER_TAG: latest
        run: |
          docker build -t "${IMAGE_NAME}:${DOCKER_TAG}" .
          echo "Built Docker image with tag: ${IMAGE_NAME}:${DOCKER_TAG}"

      - name: Push Docker Image to Docker Hub
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend
          DOCKER_TAG: latest
        run: |
          docker push "${IMAGE_NAME}:${DOCKER_TAG}"

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          # Run railway login to ensure authentication is in place
          echo $RAILWAY_TOKEN | railway login --token

      - name: Deploy to Railway
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/zero-budget-backend
          DOCKER_TAG: latest
        run: |
          # Link the Railway project using the RAILWAY_PROJECT_ID secret
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

          # Deploy the Docker image using the specific tag
          railway up --service zero-budget-backend --docker-image "${IMAGE_NAME}:${DOCKER_TAG}"
